version: "3.4"
services:
  db:
    image: mariadb
    restart: always
    env_file: vars.env
    volumes:
      - "mariadb:/var/lib/mysql"
  web:
    image: httpd
    restart: always
    env_file: vars.env


volumes:
  mariadb: